spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3305/springjpa-project
      username: root
   driver-class-name: com.mysql.jdbc.Driver
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
   #security:
      #user:
         #name: MDF
         #password: 12345
URLS:
   Authenticated: 
      WithoutRoles: /api/student/byEmail,/api/student/update,/api/student/all,/api/student/authorities
      WithBalanceRole: /api/course/**   
   Permitall: /api/student/register, /api/auth/signin
   
   
App:
   jwtSecret: VG9tbXk=
   jwtExpirationInMs: 3600000